# Meta Data for SEO

## Homepage
title = "BluBracket Documentation"
titleSeparator = "-"
titleAddition = "front page"
description = "Usage guide for BluBracket"

## Open Graph
images = ["blubracket-logo.png"]
ogLocale = "en_US"
domainTLD = "blubracket.com"
titleHome = "BluBracket documentation"

## Twitter Cards
twitterSite = "@blubracket"
twitterCreator = "@blubracket"

## JSON-LD
schemaType = "Organization"
schemaName = "BluBracket"
schemaAuthor = "Casey Bisson"
schemaAuthorTwitter = "https://twitter.com/misterbisson"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/casey-bisson-b033072/"
schemaAuthorGitHub = "https://github.com/misterbisson"
schemaLocale = "en-US"
schemaLogo = "blubracket-logo.png"
schemaLogoWidth = 808
schemaLogoHeight = 90
schemaImage = "blubracket-logo.png"
schemaImageWidth = 808
schemaImageHeight = 90
schemaTwitter = "https://twitter.com/blubracket"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/bluBracket/docs.blubracket.com/"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Footer
footer = "<a href=\"https://blubracket.com/\">BluBracket</a> code security tracks what's in your code, who has access, and where it goes"

# Feed
copyRight = "Copyright (c) 2019-2021 BluBracket"

# Alert
alert = true
alertDismissable = true
alertText = "These docs are in alpha. We're actively developing them, and we invite you to <a class=\"alert-link stretched-link\" href=\"https://github.com/BluBracket/docs.blubracket.com\">open an issue or PR with any suggestions</a>, but we're not currently allowing indexing and recommend <a class=\"alert-link stretched-link\" href=\"https://support.blubracket.com\">the docs at support.blubracket.com</a> for any production questionsat this time."

# Edit Page
# repoHost [Github | Gitea | GitLab] is used for building the edit link based on git hoster
repoHost = "GitHub"
docsRepo = "http://github.com/bluBracket/docs.blubracket.com"
docsRepoBranch = "main"
editPage = true

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = true
  bootStrapJs = true
  breadCrumb = true
  highLight = true
  kaTex = false
  collapsibleSidebar = true
  multilingualMode = false
  docsVersioning = false
