# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "TRACKS"
license = "MIT"
licenselink = "https://github.com/ageekymonk/hugo-tracks-theme/blob/master/LICENSE"
description = "Port of Tracks Theme https://www.competethemes.com/tracks/"
homepage = "https://github.com/ageekymonk/hugo-tracks-theme"
tags = ["projects", "minimal", "responsive"]
features = ["disqus", "bootstrap", "responsive", "google analytics"]
min_version = 0.10

[author]
  name = "Ramz Sivagurunathan"
  homepage = "https://github.com/ageekymonk"

# If porting an existing theme
[original]
  name = "tracks"
  homepage = "https://www.competethemes.com/tracks/"
